version: "2"

linters:
  default: none
  
  enable: # keep in ascending order
    - asasalint
    - asciicheck
    - bodyclose
    - contextcheck
    - copyloopvar
    - dupl
    - durationcheck
    - err113
    - errcheck
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - iface
    - inamedparam
    - ineffassign
    - intrange
    - lll
    - mirror
    - misspell
    - musttag
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - recvcheck
    - sloglint
    - staticcheck
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace

  settings:
    dupl:
      threshold: 100
    misspell:
      locale: US
    gocognit:
      min-complexity: 15
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 120
      tab-width: 4
    goconst:
      min-len: 3
      min-occurrences: 3
    prealloc:
      for-loops: true
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - whyNoLint

  exclusions:
    warn-unused: true
    paths:
      - mocks
    rules:
      - linters:
          - dupl
        path: _test\.go
      - linters:
          - gosec
        text: "G404:"
        path: _test\.go

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/sv-tools/mongoifc)
    gofumpt:
        extra-rules: true
