linters:
  enable: # keep in ascending order
    - asciicheck
    - bodyclose
    - copyloopvar
    - dupl
    - durationcheck
    - err113
    - exhaustive
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofumpt
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  dupl:
    threshold: 100
  misspell:
    locale: US
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/sv-tools/mongoifc)
  gocognit:
    min-complexity: 15
  gocyclo:
    min-complexity: 15
  gofumpt:
    extra-rules: true
  lll:
    line-length: 120
    tab-width: 4
  goconst:
    min-len: 3
    min-occurrences: 3
  prealloc:
    for-loops: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint

issues:
  exclude-dirs:
    - mocks
  exclude-use-default: false
  exclude:
    - should have a package comment
